//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DvdKibet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film_Rental
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film_Rental()
        {
            this.Receipt = new HashSet<Receipt>();
        }
    
        public int Id_Film_Rental { get; set; }
        public System.DateTime Date_Receipt { get; set; }
        public System.DateTime Lease_up { get; set; }
        public int Id_Client { get; set; }
        public int Id_Employee { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipt { get; set; }
    }
}
