//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DvdKibet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int Id_Receipt { get; set; }
        public int Id_Film_Rental { get; set; }
        public int Id_Film { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Film_Rental Film_Rental { get; set; }
    }
}
